import { submitQuizFormAction } from "@/actions/quiz";
import { Button } from "@/components/ui/button";
import { Card, CardTitle } from "@/components/ui/card";
import { Field, Input, Textarea } from "@/components/ui/input";
import { Notice } from "@/components/ui/notice";
import { PageHeader } from "@/components/ui/page-header";
import { requireRole } from "@/lib/auth";
import { getStore } from "@/lib/data";
import { redirect } from "next/navigation";
export default async function Page({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string }> }) { const identity=await requireRole("student"); const details=await (await getStore()).getQuiz(identity,(await params).id); if(details.existingSubmission) redirect(`/app/student/results/${details.existingSubmission.id}`); return <><PageHeader title={details.quiz.title} description={details.quiz.instructions || "أجب عن كل الأسئلة ثم راجع قبل التسليم."}/><Notice {...(await searchParams)}/><form action={submitQuizFormAction} encType="multipart/form-data" className="grid gap-5"><input type="hidden" name="quizId" value={details.quiz.id}/>{details.questions.map((question,index)=><Card key={question.id}><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-[#1479b8]">السؤال {index+1}</p><CardTitle className="mt-1">{question.prompt}</CardTitle></div><span className="text-xs font-bold text-slate-500">{question.points} درجات</span></div><div className="mt-5">{question.type === "mcq" && <div className="grid gap-3">{question.options?.map(option=><label key={option.id} className="focus-within:ring-2 focus-within:ring-sky-200 flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-4"><input type="radio" name={`question_${question.id}`} value={option.id} required={question.required}/><span>{option.text}</span></label>)}</div>}{question.type === "true_false" && <div className="grid grid-cols-2 gap-3"><label className="rounded-xl border p-4"><input type="radio" name={`question_${question.id}`} value="true" required/> صح</label><label className="rounded-xl border p-4"><input type="radio" name={`question_${question.id}`} value="false" required/> خطأ</label></div>}{question.type === "essay_text" && <Field label="إجابتك"><Textarea name={`question_${question.id}`} required={question.required}/></Field>}{question.type === "essay_file" && <Field label="ارفع PDF أو صورة أو DOCX" hint="الحد الأقصى 20MB"><Input type="file" name={`question_${question.id}`} accept="application/pdf,image/jpeg,image/png,application/vnd.openxmlformats-officedocument.wordprocessingml.document" required={question.required}/></Field>}</div></Card>)}<div className="sticky bottom-4 rounded-2xl border border-slate-200 bg-white/95 p-4 shadow-xl backdrop-blur"><Button size="lg" className="w-full">تسليم الاختبار نهائيًا</Button><p className="mt-2 text-center text-xs text-slate-500">محاولة واحدة. الأسئلة المقالية تنتظر تصحيح المعلم.</p></div></form></>; }
