import { gradeSubmissionAction } from "@/actions/quiz";
import { QuestionList } from "@/components/quiz/question-list";
import { Button } from "@/components/ui/button";
import { Card, CardDescription, CardTitle } from "@/components/ui/card";
import { Field, Input, Textarea } from "@/components/ui/input";
import { Notice } from "@/components/ui/notice";
import { PageHeader } from "@/components/ui/page-header";
import { requireRole } from "@/lib/auth";
import { getStore } from "@/lib/data";
export default async function Page({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ notice?: string; error?: string }> }) { const identity=await requireRole("teacher"); const details=await (await getStore()).getSubmission(identity,(await params).id); const manual=details.questions.filter(q=>q.type === "essay_text" || q.type === "essay_file"); return <><PageHeader title={`تصحيح: ${details.student.displayName}`} description={details.quiz.title}/><Notice {...(await searchParams)}/><div className="grid gap-6 xl:grid-cols-[1fr_380px]"><Card><QuestionList questions={details.questions} answers={details.answers} reveal/></Card><Card className="h-fit"><CardTitle>الدرجات اليدوية</CardTitle><CardDescription>أدخل درجة كل سؤال ثم اختر إصدار النتيجة.</CardDescription><form action={gradeSubmissionAction} className="mt-5 grid gap-5"><input type="hidden" name="submissionId" value={details.submission.id}/>{manual.map(question=>{ const answer=details.answers.find(a=>a.questionId===question.id); return <div key={question.id} className="rounded-xl border border-slate-200 p-4"><p className="mb-3 text-sm font-black">{question.prompt}</p><Field label={`الدرجة من ${question.points}`}><Input name={`score_${question.id}`} type="number" min={0} max={question.points} step="0.5" defaultValue={answer?.manualScore ?? 0}/></Field><div className="mt-3"><Field label="ملاحظة"><Textarea name={`feedback_${question.id}`} defaultValue={answer?.feedback}/></Field></div></div>})}<label className="flex items-center gap-3 rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800"><input type="checkbox" name="release"/> إصدار النتيجة للطالب الآن</label><Button>حفظ التصحيح</Button></form></Card></div></>; }
