import Link from "next/link";
import { BookOpen, Phone, UserRound } from "lucide-react";
import type { GroupDetails, Identity, UserRecord } from "@/domain/models";
import { CreateStudentForm } from "@/components/forms/create-user-forms";
import { TeacherFinanceNoteEditor } from "@/components/students/teacher-finance-note";
import { Button } from "@/components/ui/button";
import { Card, CardDescription, CardTitle } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Field, Input, Select, Textarea } from "@/components/ui/input";
import { LinkButton } from "@/components/ui/link-button";
import { createSubjectAction } from "@/actions/content";
import { transferGroupAction } from "@/actions/groups";

export function GroupDetailsView({ details, identity, teachers }: { details: GroupDetails; identity: Identity; teachers?: UserRecord[] }) {
  const subjectBase = `/app/${identity.role}/subjects`;
  return <div className="grid gap-6"><section className="grid gap-4 lg:grid-cols-[1fr_310px]"><Card><div className="flex flex-wrap items-start justify-between gap-4"><div><CardTitle className="text-2xl">{details.group.name}</CardTitle><CardDescription>{details.group.description || "مجموعة تعليمية خاصة"}</CardDescription></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">{details.group.status === "active" ? "نشطة" : "غير نشطة"}</span></div><div className="mt-6 flex items-center gap-3 rounded-xl bg-slate-50 p-4"><UserRound className="size-5 text-[#1479b8]"/><div><p className="text-xs text-slate-500">المعلم المسؤول</p><p className="font-black">{details.owner?.displayName || "غير محدد"}</p></div></div></Card>{identity.role === "admin" && <Card><CardTitle>نقل الملكية</CardTitle><CardDescription>المعلم القديم يفقد الوصول فورًا.</CardDescription><form action={transferGroupAction} className="mt-5 grid gap-4"><input type="hidden" name="groupId" value={details.group.id}/><input type="hidden" name="returnTo" value={`/app/admin/groups/${details.group.id}`}/><Field label="المعلم الجديد"><Select name="ownerTeacherId" required defaultValue={details.group.ownerTeacherId}>{teachers?.map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.displayName}</option>)}</Select></Field><Button variant="secondary">تأكيد النقل</Button></form></Card>}</section>
  <section className="grid gap-6 xl:grid-cols-[1fr_380px]"><div className="grid gap-6"><Card><div className="flex items-center justify-between"><div><CardTitle>المواد</CardTitle><CardDescription>كل مادة داخل هذه المجموعة فقط.</CardDescription></div></div><div className="mt-5 grid gap-3">{details.subjects.length ? details.subjects.map((subject) => <Link key={subject.id} href={`${subjectBase}/${subject.id}`} className="focus-ring flex items-center justify-between rounded-xl border border-slate-200 p-4 hover:bg-sky-50/50"><span className="flex items-center gap-3 font-bold"><BookOpen className="size-5 text-[#1479b8]"/>{subject.title}</span><span className="text-xs text-slate-400">فتح</span></Link>) : <EmptyState title="لا توجد مواد" description={identity.role === "teacher" ? "أضف المادة الأولى من النموذج المجاور." : "لم يضف المعلم مواد بعد."}/>}</div></Card><Card><CardTitle>الطلاب</CardTitle><CardDescription>{identity.role === "student" ? "قائمة الطلاب مخفية لحماية الخصوصية." : "طلاب هذه المجموعة فقط."}</CardDescription>{identity.role !== "student" && <div className="mt-5 grid gap-3">{details.students.length ? details.students.map((student) => { const privateRecord=details.privateRecords.find((record) => record.studentId === student.id); return <div key={student.id} className="rounded-xl border border-slate-200 p-4"><p className="font-black">{student.displayName}</p>{privateRecord?.contactNumber && <div className="mt-3 flex flex-wrap gap-3 text-xs text-slate-500"><span className="inline-flex items-center gap-1"><Phone className="size-3.5"/>{privateRecord.contactNumber}</span></div>}{identity.role === "teacher" && <TeacherFinanceNoteEditor teacherId={identity.userId} groupId={details.group.id} studentId={student.id}/>}</div>; }) : <EmptyState title="لا يوجد طلاب"/>}</div>}</Card></div>
  {identity.role === "teacher" && <div className="grid content-start gap-6"><Card><CardTitle>مادة جديدة</CardTitle><form action={createSubjectAction} className="mt-5 grid gap-4"><input type="hidden" name="groupId" value={details.group.id}/><input type="hidden" name="returnTo" value={`/app/teacher/groups/${details.group.id}`}/><Field label="اسم المادة"><Input name="title" required/></Field><Field label="وصف مختصر"><Textarea name="description"/></Field><Button>إضافة المادة</Button></form></Card><Card><CardTitle>طالب جديد</CardTitle><div className="mt-5"><CreateStudentForm groups={[details.group]} fixedGroupId={details.group.id} returnTo={`/app/teacher/groups/${details.group.id}`} teacherId={identity.userId}/></div></Card></div>}
  {identity.role === "student" && <Card><CardTitle>ما الذي يظهر لك؟</CardTitle><CardDescription>المواد والدروس المنشورة فقط. بيانات المعلم والطلاب والملاحظات المالية غير موجودة في واجهتك.</CardDescription><div className="mt-5"><LinkButton href="/app/student/groups" variant="secondary">العودة إلى فصولي</LinkButton></div></Card>}</section></div>;
}
